2020-05-24 19:53:04,592 ERROR: Exception on /user/toto [GET] [in /home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ioan/bin/microblog/app/routes.py", line 70, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ioan/bin/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ioan/bin/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ioan/bin/microblog/app/templates/user.html", line 18, in block "content"
    {{ form.submit(value='Follow') }}
jinja2.exceptions.UndefinedError: 'app.forms.EmptyForm object' has no attribute 'submit'
2020-05-24 19:55:53,964 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:30]
2020-05-24 19:56:36,838 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:30]
2020-05-24 19:56:55,867 ERROR: Exception on /user/toto [GET] [in /home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ioan/bin/microblog/app/routes.py", line 70, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ioan/bin/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ioan/bin/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ioan/bin/microblog/app/templates/user.html", line 18, in block "content"
    {{ form.submit(value='Follow') }}
jinja2.exceptions.UndefinedError: 'app.forms.EmptyForm object' has no attribute 'submit'
2020-05-24 20:00:06,402 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:30]
2020-05-24 20:00:15,068 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:30]
2020-05-24 20:00:43,156 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:30]
2020-05-24 20:00:56,469 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:30]
2020-05-24 20:01:03,190 ERROR: Exception on /user/toto [GET] [in /home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ioan/bin/microblog/app/routes.py", line 71, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ioan/bin/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ioan/bin/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ioan/bin/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ioan/bin/microblog/app/templates/user.html", line 18, in block "content"
    {{ form.submit(value='Follow') }}
jinja2.exceptions.UndefinedError: 'app.forms.EmptyForm object' has no attribute 'submit'
2020-05-25 13:36:09,245 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:30]
2020-05-26 17:43:31,791 INFO: Microblog startup [in /home/ioan/bin/microblog/app/__init__.py:32]
2020-07-02 14:09:57,940 INFO: Microblog startup [in /home/ioan/binn/microblog/app/__init__.py:32]
2020-07-02 14:10:03,562 INFO: Microblog startup [in /home/ioan/binn/microblog/app/__init__.py:32]
2020-07-02 14:10:14,273 INFO: Microblog startup [in /home/ioan/binn/microblog/app/__init__.py:32]
2020-07-02 14:10:23,459 INFO: Microblog startup [in /home/ioan/binn/microblog/app/__init__.py:32]
2020-07-02 14:12:26,969 INFO: Microblog startup [in /home/ioan/binn/microblog/app/__init__.py:32]
